name: "Feature request"
description: "Suggest an idea for this project"
title: "[Feature Request] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open a feature request! Please provide the following information:

  - type: input
    id: feature_name
    attributes:
      label: "Feature Name"
      description: "What is the name of the feature you are requesting?"
      placeholder: "Enter feature name"

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Please describe the feature you would like to see."
      placeholder: "Enter feature description"

  - type: textarea
    id: feature_benefits
    attributes:
      label: "Feature Benefits"
      description: "Explain how this feature will benefit users or improve the project."
      placeholder: "Describe the benefits"

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Describe any alternative solutions or features you've considered."
      placeholder: "Enter alternatives"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Enter additional context"
